import "dotenv/config";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import { PrismaClient } from "../app/generated/prisma/client";

const adapter = new PrismaBetterSqlite3({ url: process.env.DATABASE_URL ?? "file:./prisma/main.db" });
const prisma = new PrismaClient({ adapter });

async function main() {
  await prisma.link.deleteMany();
  await prisma.section.deleteMany();
  await prisma.tab.deleteMany();
  await prisma.dashboard.deleteMany();

  const dashboard = await prisma.dashboard.create({
    data: {
      id: 1,
      title: "My Dashboard",
      subtitle: "Your aesthetic bookmark collection",
      titleGradientFrom: "#f9a8d4",
      titleGradientVia: "#d8b4fe",
      titleGradientTo: "#93c5fd",
      backgroundImage: "/defaults/background.jpg",
      bgOverlayFrom: "#581c8766",
      bgOverlayVia: "#831843",
      bgOverlayTo: "#1e3a8a66",
      bgOverlayOpacity: 1,
      theme: "mocha",
      showTitle: true,
      showSubtitle: true,
      titleColor: null,
      backgroundBlur: 5,
      tabBarPosition: "bottom",
      settingsShowIcon: true,
      settingsShowTitle: true,
      settingsButtonType: "ghost",
      settingsButtonSize: "sm",
      settingsBorderWidth: 0,
      settingsBorderStyle: "solid",
      settingsBorderColor: null,
      settingsBgColor: null,
      settingsBgOpacity: 1,
      settingsBgImage: null,
      shortcutShowIndicators: true,
      shortcutLinkScope: "tab",
      shortcutKbdSize: "sm",
    },
  });

  const tabsSeed = [
    {
      slug: "home",
      label: "Home",
      icon: "LuHouse",
      order: 0,
      pillGradientFrom: "#ec4898",
      pillGradientTo: "#a855f7",
      sideImage: "https://picsum.photos/seed/home/800/1200",
      sideImageAlt: "Home",
      sideImageEdge: "gradient",
      showSideImage: true,
      bgColor: null,
      bgOpacity: 1,
      bgImage: null,
      borderWidth: 0,
      borderStyle: "solid",
      borderColor: null,
      sectionColumns: 1,
      linkColumns: 2,
      headerTitle: "",
      headerVAlign: "top",
      headerHAlign: "center",
      headerColor: null,
      headerSize: "2xl",
      headerWeight: "bold",
      pillBgColor: null,
      pillBgOpacity: 1,
      pillBgImage: null,
      pillShowIcon: true,
      pillShowTitle: true,
      pillTitleColor: null,
      pillTitleSize: "sm",
      pillTitleWeight: "medium",
      shortcutKey: "h",
      sections: [
        {
          title: "Productivity",
          icon: "LuCalendar",
          order: 0,
          showIcon: true,
          showTitle: true,
          iconSize: "sm",
          titleSize: "xs",
          titleWeight: "semibold",
          titleColor: null,
          borderWidth: 0,
          borderStyle: "solid",
          borderColor: null,
          bgColor: null,
          bgOpacity: 1,
          bgImage: null,
          links: [
            {
              icon: "LuMail",
              title: "Gmail",
              description: "Email & communication",
              href: "https://mail.google.com",
              newTab: true,
              showIcon: true,
              showTitle: true,
              showDescription: true,
              bgColor: null,
              bgOpacity: 1,
              bgImage: null,
              borderWidth: 0,
              borderStyle: "solid",
              borderColor: null,
              textAlign: "left",
              titleSize: "sm",
              titleWeight: "medium",
              textColor: null,
              shortcutKey: "g",
              order: 0,
            },
            {
              icon: "LuCalendar",
              title: "Google Calendar",
              description: "Schedule & events",
              href: "https://calendar.google.com",
              newTab: true,
              showIcon: true,
              showTitle: true,
              showDescription: true,
              bgColor: null,
              bgOpacity: 1,
              bgImage: null,
              borderWidth: 0,
              borderStyle: "solid",
              borderColor: null,
              textAlign: "left",
              titleSize: "sm",
              titleWeight: "medium",
              textColor: null,
              shortcutKey: "c",
              order: 1,
            },
          ],
        },
      ],
    },
    {
      slug: "entertainment",
      label: "Entertainment",
      icon: "LuSparkles",
      order: 1,
      pillGradientFrom: "#ec4899",
      pillGradientTo: "#a855f7",
      sideImage: "https://picsum.photos/seed/fun/800/1200",
      sideImageAlt: "Entertainment",
      sideImageEdge: "gradient",
      showSideImage: true,
      bgColor: null,
      bgOpacity: 1,
      bgImage: null,
      borderWidth: 0,
      borderStyle: "solid",
      borderColor: null,
      sectionColumns: 1,
      linkColumns: 2,
      headerTitle: "",
      headerVAlign: "top",
      headerHAlign: "center",
      headerColor: null,
      headerSize: "2xl",
      headerWeight: "bold",
      pillBgColor: null,
      pillBgOpacity: 1,
      pillBgImage: null,
      pillShowIcon: true,
      pillShowTitle: true,
      pillTitleColor: null,
      pillTitleSize: "sm",
      pillTitleWeight: "medium",
      shortcutKey: "e",
      sections: [
        {
          title: "Media",
          icon: "LuTv",
          order: 0,
          showIcon: true,
          showTitle: true,
          iconSize: "sm",
          titleSize: "xs",
          titleWeight: "semibold",
          titleColor: null,
          borderWidth: 0,
          borderStyle: "solid",
          borderColor: null,
          bgColor: null,
          bgOpacity: 1,
          bgImage: null,
          links: [
            {
              icon: "LuVideo",
              title: "YouTube",
              description: "Videos & creators",
              href: "https://youtube.com",
              newTab: true,
              showIcon: true,
              showTitle: true,
              showDescription: true,
              bgColor: null,
              bgOpacity: 1,
              bgImage: null,
              borderWidth: 0,
              borderStyle: "solid",
              borderColor: null,
              textAlign: "left",
              titleSize: "sm",
              titleWeight: "medium",
              textColor: null,
              shortcutKey: "y",
              order: 0,
            },
          ],
        },
        {
          title: "Gaming",
          icon: "LuGamepad2",
          order: 1,
          showIcon: true,
          showTitle: true,
          iconSize: "sm",
          titleSize: "xs",
          titleWeight: "semibold",
          titleColor: null,
          borderWidth: 0,
          borderStyle: "solid",
          borderColor: null,
          bgColor: null,
          bgOpacity: 1,
          bgImage: null,
          links: [
            {
              icon: "LuGamepad2",
              title: "Chess.com",
              description: "Online chess",
              href: "https://chess.com",
              newTab: true,
              showIcon: true,
              showTitle: true,
              showDescription: true,
              bgColor: null,
              bgOpacity: 1,
              bgImage: null,
              borderWidth: 0,
              borderStyle: "solid",
              borderColor: null,
              textAlign: "left",
              titleSize: "sm",
              titleWeight: "medium",
              textColor: null,
              shortcutKey: "s",
              order: 0,
            },
          ],
        },
      ],
    },
  ];

  for (const t of tabsSeed) {
    const { sections, ...tabData } = t;
    const tab = await prisma.tab.create({ data: { ...tabData, dashboardId: dashboard.id } });
    for (const s of sections) {
      const { links, ...sectionData } = s;
      const section = await prisma.section.create({ data: { ...sectionData, tabId: tab.id } });
      for (const l of links) {
        await prisma.link.create({ data: { ...l, sectionId: section.id } });
      }
    }
  }

  console.log("Seed complete.");
}

main().finally(() => prisma.$disconnect());
