import type { IconType } from "react-icons";
import {
  LuHouse,
  LuBriefcase,
  LuSparkles,
  LuFlower2,
  LuGithub,
  LuMail,
  LuCalendar,
  LuFileText,
  LuCloud,
  LuTrello,
  LuMessageSquare,
  LuVideo,
  LuMusic,
  LuGamepad2,
  LuTv,
  LuBookOpen,
  LuBrain,
  LuHeart,
  LuMoon,
  LuSunMedium,
  LuStar,
  LuBookmark,
  LuCompass,
  LuCamera,
  LuImage,
  LuCode,
  LuTerminal,
  LuDatabase,
  LuServer,
  LuGlobe,
  LuLink,
  LuMap,
  LuMapPin,
  LuUser,
  LuUsers,
  LuShoppingCart,
  LuCreditCard,
  LuDollarSign,
  LuCoffee,
  LuPizza,
  LuUtensils,
  LuCar,
  LuPlane,
  LuBike,
  LuDumbbell,
  LuActivity,
  LuMusic2,
  LuHeadphones,
  LuFilm,
  LuPodcast,
  LuNewspaper,
  LuRss,
  LuFeather,
  LuPenTool,
  LuPalette,
  LuBell,
  LuSettings,
  LuSearch,
  LuZap,
  LuRocket,
  LuTrophy,
  LuGift,
  LuLeaf,
  LuTrees,
  LuWaves,
  LuCloudRain,
  LuSunrise,
  LuSunset,
} from "react-icons/lu";

export const iconMap: Record<string, IconType> = {
  LuHouse, LuBriefcase, LuSparkles, LuFlower2, LuGithub, LuMail, LuCalendar,
  LuFileText, LuCloud, LuTrello, LuMessageSquare, LuVideo, LuMusic, LuGamepad2,
  LuTv, LuBookOpen, LuBrain, LuHeart, LuMoon, LuSunMedium, LuStar, LuBookmark,
  LuCompass, LuCamera, LuImage, LuCode, LuTerminal, LuDatabase, LuServer,
  LuGlobe, LuLink, LuMap, LuMapPin, LuUser, LuUsers, LuShoppingCart,
  LuCreditCard, LuDollarSign, LuCoffee, LuPizza, LuUtensils, LuCar, LuPlane,
  LuBike, LuDumbbell, LuActivity, LuMusic2, LuHeadphones, LuFilm, LuPodcast,
  LuNewspaper, LuRss, LuFeather, LuPenTool, LuPalette, LuBell, LuSettings,
  LuSearch, LuZap, LuRocket, LuTrophy, LuGift, LuLeaf, LuTrees, LuWaves,
  LuCloudRain, LuSunrise, LuSunset,
};

export const iconNames = Object.keys(iconMap);

export const resolveIcon = (name: string): IconType => iconMap[name] ?? LuBookmark;

// necessary because a icon can be from the map,
// uploaded image or pulled from the site then uploaded

export const isImageIcon = (name: string): boolean => /^(https?:\/\/|\/|data:)/.test(name);
